# frozen_string_literal: true
module LilaShell
class Room < Model
  one_to_many :messages, :order=>Sequel.desc(:at), :eager=>:user
  one_to_many :recent_messages, :clone=>:messages, :limit=>50
end
end

# Table: rooms
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    | NOT NULL
# Indexes:
#  rooms_pkey     | PRIMARY KEY btree (id)
#  rooms_name_key | UNIQUE btree (name)
# Referenced By:
#  messages | messages_room_id_fkey | (room_id) REFERENCES rooms(id)
