# frozen_string_literal: true
module LilaShell
class User < Model
end
end

# Table: users
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    | NOT NULL
# Indexes:
#  users_pkey     | PRIMARY KEY btree (id)
#  users_name_key | UNIQUE btree (name)
# Referenced By:
#  messages | messages_user_id_fkey | (user_id) REFERENCES users(id)
